services:
  postgres:
    image: 'postgres:18'
    env_file:
      - .env
    environment:
      - 'TZ=America/Sao_Paulo'
      - postgres:/var/lib/postgresql/18/docker
    ports:
      - '5432:5432'

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - '8025:8025'
      - '1025:1025'
    environment:
      - 'TZ=America/Sao_Paulo'
      - 'MP_SMTP_AUTH_ACCEPT_ANY=1'
      - 'MP_SMTP_AUTH_ALLOW_INSECURE=1'
    volumes:
      - mailpit:/data

volumes:
  postgres:
  mailpit:
